const API_BASE_URL = 'http://localhost:3200/api'
const REGISTER_ROUTE = '/customers/register';
const LOGIN_ROUTE = '/customers/login';
const ACCUSES_TOKEN_ROUTE = '/customers/accuses';
const LOGOUT_ROUT = '/customers/logout'
const IS_LOGGED_IN_ROUT = '/customers/checkAuth'
const USERNAME_EXISTS = '/customers/username-exists/'
const PROFILE_ROUTE = '/profiles';
const CATEGORY_ROUTE = '/category';
const PRODUCTS_ROUTE = '/products';


export const environment = {
  production: false,
  REGISTER_ROUTE:`${API_BASE_URL}${REGISTER_ROUTE}`,
  LOGIN_ROUTE:`${API_BASE_URL}${LOGIN_ROUTE}`,
  ACCUSES_TOKEN_ROUTE:`${API_BASE_URL}${ACCUSES_TOKEN_ROUTE}`,
  LOGOUT_ROUT:`${API_BASE_URL}${LOGOUT_ROUT}`,
  IS_LOGGED_IN_ROUT:`${API_BASE_URL}${IS_LOGGED_IN_ROUT}`,
  USERNAME_EXISTS:`${API_BASE_URL}${USERNAME_EXISTS}`,
  PROFILE_ROUTE:`${API_BASE_URL}${PROFILE_ROUTE}`,
  CATEGORY_ROUTE:`${API_BASE_URL}${CATEGORY_ROUTE}`,
  PRODUCTS_ROUTE:`${API_BASE_URL}${PRODUCTS_ROUTE}`,
  // USER_ROUTE:`${API_BASE_URL}${USER_ROUTE}`,
  // USERS_ROUTE:`${API_BASE_URL}${USERS_ROUTE}`,
  // USERDATA_ROUTE:`${API_BASE_URL}${USERDATA_ROUTE}`,
  // IMAGECHANGE_ROUTE:`${API_BASE_URL}${IMAGECHANGE_ROUTE}`,
  // NEWIMAGE_ROUTE:`${API_BASE_URL}${NEWIMAGE_ROUTE}`,
  // CONTACT_ROUTE:`${API_BASE_URL}${CONTACT_ROUTE}`,
};

